# Generated by Django 5.0.7 on 2024-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0003_alter_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
