# Generated by Django 5.0.7 on 2024-07-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0004_invoice_batch_subscriber_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='batch',
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'مسددة'), ('Partially Paid', 'مسددة جزئيا'), ('Unpaid', 'غير مسددة')], default='Unpaid', max_length=20),
        ),
    ]
