# Generated by Django 5.0.7 on 2024-07-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0005_remove_invoice_batch_invoice_balance_invoice_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
