# Generated by Django 5.0.7 on 2024-07-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0008_alter_subscriber_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='batch',
            new_name='Subscriber_balance',
        ),
    ]
