# Generated by Django 5.0.7 on 2024-07-30 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0009_rename_batch_subscriber_subscriber_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='Subscriber_balance',
            new_name='subscriber_balance',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting_system.subscriber'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
