# Generated by Django 5.0.7 on 2024-08-01 18:21

import django.db.models.deletion
import django_jsonfield_backport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0010_rename_subscriber_balance_subscriber_subscriber_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cash', 'كاش'), ('Credit Card', 'كريدت كارد'), ('Bank Transfer', 'حوالة بنكية'), ('Western Union', 'ويسترن يونيون')], max_length=50, verbose_name='طريقة الدفع')),
                ('additional_fields', django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name='الحقول الإضافية')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'عنصر الفاتورة', 'verbose_name_plural': 'عناصر الفاتورة'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'اشتراك', 'verbose_name_plural': 'الاشتراكات'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'مشترك', 'verbose_name_plural': 'المشتركون'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_details',
            field=django_jsonfield_backport.models.JSONField(blank=True, null=True, verbose_name='تفاصيل الدفع'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='المرفق'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الرصيد'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting_system.subscriber', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الدفعة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'مسددة'), ('Partially Paid', 'مسددة جزئيا'), ('Unpaid', 'غير مسددة')], default='Unpaid', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting_system.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_system.subscribe', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_balance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رصيد المشترك'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_system.paymentmethod', verbose_name='طريقة الدفع'),
        ),
    ]
