# Generated by Django 5.0.7 on 2024-08-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0011_paymentmethod_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
