# Generated by Django 5.0.7 on 2024-08-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0012_invoice_account_number_invoice_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='beneficiary_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_details',
        ),
    ]
