# Generated by Django 5.0.7 on 2024-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0013_remove_invoice_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستفيد'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم حامل البطاقة'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='رقم بطاقة الائتمان'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='رمز CVV'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='الايبان'),
        ),
    ]
