# Generated by Django 5.0.7 on 2024-08-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0014_paymentmethod_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='additional_fields',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='الرابط'),
        ),
    ]
