# Generated by Django 5.0.7 on 2024-08-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_performancereport_in_progress_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, verbose_name='التعليقات'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
